// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8hfKpO0HHaPHfcd338DKI5X4BZwHFSY8',
    appId: '1:162717958812:web:63fb4bde3e53115e0c6359',
    messagingSenderId: '162717958812',
    projectId: 'task-297cb',
    authDomain: 'task-297cb.firebaseapp.com',
    storageBucket: 'task-297cb.firebasestorage.app',
    measurementId: 'G-0HS7M843CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALygryVWXPEZWpgmWes4HnmyAR1u4NWE',
    appId: '1:162717958812:android:015b8fd2927629c10c6359',
    messagingSenderId: '162717958812',
    projectId: 'task-297cb',
    storageBucket: 'task-297cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwOht3oLKjfjbF2oQzUxXkgFYFB-3dDI',
    appId: '1:162717958812:ios:f2f108ea35c029910c6359',
    messagingSenderId: '162717958812',
    projectId: 'task-297cb',
    storageBucket: 'task-297cb.firebasestorage.app',
    iosBundleId: 'com.task.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwOht3oLKjfjbF2oQzUxXkgFYFB-3dDI',
    appId: '1:162717958812:ios:f2f108ea35c029910c6359',
    messagingSenderId: '162717958812',
    projectId: 'task-297cb',
    storageBucket: 'task-297cb.firebasestorage.app',
    iosBundleId: 'com.task.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8hfKpO0HHaPHfcd338DKI5X4BZwHFSY8',
    appId: '1:162717958812:web:d13529309b8d83140c6359',
    messagingSenderId: '162717958812',
    projectId: 'task-297cb',
    authDomain: 'task-297cb.firebaseapp.com',
    storageBucket: 'task-297cb.firebasestorage.app',
    measurementId: 'G-Z2DSZE1VZK',
  );
}
